// <auto-generated />
using BakersAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakersAPI.Migrations
{
    [DbContext(typeof(BakerContext))]
    partial class BakerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakersAPI.Models.Bakeritem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BakerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BakerItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BakerName = "Chef_Bongi",
                            Description = "Carrot cake is moist, light, fluffy, and topped with a rich cream cheese frosting.Very moist and very tasty, will buy this cake again.Absolutely delicious! The main beauty is that it only comes in a larger size and square cup-cake size as a platter too, which can be a stunning dessert",
                            ImageUrl = "https://www.allrecipes.com/thmb/hz54Dw9cCRehCTe6ZyF2IGeRo9Y=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/7402-carrot-cake-iii-sarah-dipity-1x1-1-2e7c90d8c07c47039b4906ec01911015.jpg",
                            IsDone = false,
                            Name = "Chees Cake",
                            Price = 1200
                        },
                        new
                        {
                            Id = 2L,
                            BakerName = "Chef_Bongi",
                            Description = "Soaking the chocolate sponge in sugar syrup flavored with cherry brandy and topped with whipped cream and gelatin, or cornstarch.",
                            ImageUrl = "https://bon.sitenet.co.za/wp-content/uploads/2022/08/cooking-school-in-pretoria-1536x816.png",
                            IsDone = false,
                            Name = "Black Forest Cake ",
                            Price = 1800
                        },
                        new
                        {
                            Id = 3L,
                            BakerName = "Chef_Annah",
                            Description = "Deep and rich, red velvet cake is a mild chocolate confection. cocoa flavor, As for frosting, Our cream cheese.",
                            ImageUrl = "https://funcakes.com/content/uploads/2021/02/Red-Velvet-Cake-with-Fruit-960x960-c-default.jpg",
                            IsDone = false,
                            Name = "Red Velvet Cake ",
                            Price = 1450
                        },
                        new
                        {
                            Id = 4L,
                            BakerName = "Chef_Ria",
                            Description = "Filled and coated in a wonderful strawberry cream cheese frosting, this cake has strawberry flavoring through and through.This strawberry cheesecake is a wonderful combination of rich, creamy New York cheesecake and bright, homemade strawberry sauce! It makes the best summertime dessert and is perfect for using those fresh, ripe, seasonal strawberries.",
                            ImageUrl = "https://preppykitchen.com/wp-content/uploads/2022/05/Strawberry-Cake-Recipe-Card.jpg",
                            IsDone = false,
                            Name = "Strawberry Cake ",
                            Price = 1050
                        },
                        new
                        {
                            Id = 5L,
                            BakerName = "Chef_Annah",
                            Description = "Strawberry Cake, Red velvet cake and Carrot Cake.",
                            ImageUrl = "https://bon.sitenet.co.za/wp-content/uploads/2022/08/bonaria-baking-school-in-pretoria-1024x683.png",
                            IsDone = false,
                            Name = "Mixed Cake Platter ",
                            Price = 3300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
